# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Charts

on:
  push:
    branches: [ master ]
  schedule:
      # Depends on csv file generated daily at 14:21-14:22-ish.
      # UTC is currently -2 wrt Europe/Stockholm (CEST).
      - cron: "23,55 12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Generate charts
      run: |
        python generate-html-charts.py
#    - name: Commit updated charts
#      run: |
#        git config --global user.name 'Niklas Morberg'
#        git config --global user.email 'morberg@users.noreply.github.com'
#        git commit -am "Automated chart update" --allow-empty
#        git push
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic update of charts
