# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  schedule:
      # Depends on csv file generated daily at 14:02 and 14:30.
      # @adamaltmejd's job takes 10-15 minutes to finish.
      # UTC is currently -2 wrt Europe/Stockholm (CEST).
      - cron: "17,45 12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate charts
      run: |
        python generate-html-charts.py
    - name: Commit updated charts
      run: |
        git config --global user.name 'Niklas Morberg'
        git config --global user.email 'morberg@users.noreply.github.com'
        git commit -am "Automated chart update"
        git push
    #- name: Lint with flake8
      #run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
      #run: |
        #pytest
